---
repos:
  - repo: local
    hooks:
      - id: blacken-docs
        name: "â˜•ï¸ Format documentation using black"
        language: system
        files: '\.(rst|md|markdown|py|tex)$'
        entry: uv run blacken-docs
        require_serial: true
      - id: check-ast
        name: "ğŸ Checking Python AST"
        language: system
        types: [python]
        entry: uv run check-ast
      - id: check-case-conflict
        name: "ğŸ”  Checking for case conflicts"
        language: system
        entry: uv run check-case-conflict
      - id: check-docstring-first
        name: "â„¹ï¸  Checking docstrings are first"
        language: system
        types: [python]
        entry: uv run check-docstring-first
      - id: check-executables-have-shebangs
        name: "ğŸ§ Checking that executables have shebangs"
        language: system
        types: [text, executable]
        entry: uv run check-executables-have-shebangs
        stages: [pre-commit, pre-push, manual]
      - id: check-json
        name: "ï½› Checking JSON files"
        language: system
        types: [json]
        entry: uv run check-json
      - id: check-merge-conflict
        name: "ğŸ’¥ Checking for merge conflicts"
        language: system
        types: [text]
        entry: uv run check-merge-conflict
      - id: check-symlinks
        name: "ğŸ”— Checking for broken symlinks"
        language: system
        types: [symlink]
        entry: uv run check-symlinks
      - id: check-toml
        name: "âœ… Checking TOML files"
        language: system
        types: [toml]
        entry: uv run check-toml
      - id: codespell
        name: "âœ… Checking code for misspellings"
        language: system
        types: [text]
        exclude: |
          (?x)^($^
          |.*uv\.lock
          )$
        entry: uv run codespell
      - id: debug-statements
        name: "ğŸªµ Checking for debug statements and imports (Python)"
        language: system
        types: [python]
        entry: uv run debug-statement-hook
      - id: detect-private-key
        name: "ğŸ•µï¸  Detecting private keys"
        language: system
        types: [text]
        entry: uv run detect-private-key
      - id: end-of-file-fixer
        name: "ğŸ”š Checking end of files"
        language: system
        types: [text]
        entry: uv run end-of-file-fixer
        stages: [pre-commit, pre-push, manual]
      - id: fix-byte-order-marker
        name: "ğŸš Checking UTF-8 byte order marker"
        language: system
        types: [text]
        entry: uv run fix-byte-order-marker
      - id: format
        name: "â˜•ï¸ Formatting code using ruff"
        language: system
        types: [python]
        entry: uv run ruff format
      - id: mypy
        name: "ğŸ† Performing static type checking using mypy"
        language: system
        types: [python]
        entry: uv run mypy
      - id: no-commit-to-branch
        name: "ğŸ›‘ Checking for commit to protected branch"
        language: system
        entry: uv run no-commit-to-branch
        pass_filenames: false
        always_run: true
        args:
          - --branch=development
          - --branch=main
      - id: pylint
        name: "ğŸŒŸ Starring code with pylint"
        language: system
        types: [python]
        entry: uv run pylint
      - id: ruff
        name: "ğŸ‘” Enforcing style guide with ruff"
        language: system
        types: [python]
        entry: uv run ruff check --fix
        require_serial: true
      - id: trailing-whitespace
        name: "âœ„  Trimming trailing whitespace"
        language: system
        types: [text]
        entry: uv run trailing-whitespace-fixer
        stages: [pre-commit, pre-push, manual]
      - id: uv-lock
        name: "ğŸ”’ Ensure the uv.lock file is up to date"
        language: system
        entry: uv lock --locked
        files: pyproject.toml$
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        name: "ğŸ’„ Ensuring files are prettier"
